### PR TITLE
Fix quotation marks in f-string

### PR DESCRIPTION
**Pull request by dolph**
Closes: https://github.com/LukeCarrier/mkdocs-drawio-exporter/issues/59

### CODE REVIEW

**Comment by ConnorTroy** [comment]
It appears that there are several other f-strings with the same issue: https://github.com/LukeCarrier/mkdocs-drawio-exporter/compare/main...ConnorTroy:mkdocs-drawio-exporter:f-string-quotes

**Comment by mriedem** [comment]
Thanks for posting this. @LukeCarrier have you thought about running `flake8` or some other static code check during CI runs?

**Comment by LukeCarrier** [comment]
Hey, thanks for fixing this. I'm happy to review any CI and release improvements but have barely enough time to maintain this as is.

In this case having a wider test matrix covering older Python versions prior to 3.12 would have caught this, and that's a quick win here.

**Comment by LukeCarrier** [comment]
Have taken @ConnorTroy's linked diff above and added a missing `__future__` annotation for the typings introduced in 0.9.0, both in #62. #61 should ensure I don't break everyone again in the next release :-)

**Pull request closed without merging**
