### PR TITLE
Inline SVG embed format

### PR DESCRIPTION
**Pull request by herberton**
Hi @LukeCarrier ,

I work at [TOTVS](https://www.totvs.com/), from Brazil, and we use the  `mkdocs-drawio-exporter` plugin in our `mkdocs` documentation (thanks a lot). We are putting this documentation to be displayed inside [backstage.io](https://backstage.io/) and we are faced with the challenge since, for security reasons, the [backstage.io techdocs](https://backstage.io/docs/features/techdocs/techdocs-overview) plugin removes the `<object/>`, `<embed/>`, `<iframe/>` and some other HTML tags by default (they are using [DOM Purify](https://github.com/cure53/DOMPurify)).

After studying alternatives to solve this problem, we decided to package our `mkdocs` documentation differently, embedding the SVG content inside the HTML body. So, I forked your project by enabling this new embedding format (which I called `html`).

Basically, you need to configure `mkdocs-drawio-exporter` as follows:

```yaml
plugins:
    - drawio-exporter:
        format: svg
        embed_format: html
```

To enable this functionality I had to change the order of some things, so the plugin starts generating the SVGs in the `on_post_page` event and before changing the HTML body. I had to do this to be able to [embed the SVG inside the HTML body](https://github.com/herberton/mkdocs-drawio-exporter/blob/master/mkdocsdrawioexporter/exporter.py#L318).

I also reorganized the source code in order to isolate the responsibilities between [exporter.py](https://github.com/herberton/mkdocs-drawio-exporter/blob/master/mkdocsdrawioexporter/exporter.py) and [plugin.py](https://github.com/herberton/mkdocs-drawio-exporter/blob/master/mkdocsdrawioexporter/plugin.py) in order to simplify usage, reducing parameter passing and promote better maintainability.

I hope to be able to activate these changes in the next version,

Herberton.

### CODE REVIEW

**Review by herberton — COMMENTED** [review]
Hi @LukeCarrier , can you approve this PR?

**Comment by LukeCarrier** [comment]
Hey @herberton,Thanks for the work on this. Given the size of the diff I really need to review the change properly, but I am snowed under with work right now.You’re welcome to fork and publish to PyPI yourself if you need this immediately.On 10 Nov 2022, at 02:23, Herberton Candido Souza ***@***.***> wrote:﻿
@herberton commented on this pull request.

Hi @LukeCarrier , can you approve this PR?

**Comment by herberton** [comment]
Hi @LukeCarrier , I found a little bug but I already fix it!!!

**Comment by LukeCarrier** [comment]
Fixes #44

**Comment by LukeCarrier** [comment]
Hey @herberton, hope you're well. Sorry for the delay in getting around to this change!

I didn't want to break the convention we have of letting users specify their own `embed_format`s using template strings, so in #56 I've introduced a new `content` value.As the diff for this approach is smaller I'm going to close this PR in favour of the other one.

Many thanks for the idea and implementation, and I hope you're happy with this approach!

**Pull request closed without merging**
